/**
 * Loads PixelLab sprites for the RPG.
 * Falls back to procedural drawing when an image is missing.
 *
 * Player/NPC direction sprites: static/game/rafe/<dir>.png holds the rotatable
 * sprite set (south, east, north, west — generated by PixelLab rotations).
 * Walk animation strips: static/game/rafe/walk/<dir>-<i>.png (one file per frame).
 * Older flat sprites (rafe.png …) stay as fallbacks.
 */

/** @type {Record<string, CanvasImageSource>} */
const images = {};

/** Wang corner → sheet rect lookup, filled from tileset.json. */
/** @type {Record<string, {x: number, y: number, w: number, h: number}>} */
let wangTiles = {};

/** @type {Promise<void> | null} */
let loadPromise = null;

const SPRITE_URLS = {
	rafe: '/game/rafe.png',
	zeno: '/game/zeno.png',
	erebus: '/game/erebus.png',
	nala: '/game/nala.png',
	razel: '/game/razel.png',
	tidekeeper: '/game/tidekeeper.png',
	shade: '/game/shade.png',
	fountain: '/game/fountain.png',
	tileset: '/game/tileset.png'
};

/** Cardinal directions we render (game movement is 4-way). */
export const DIRS = ['south', 'east', 'north', 'west'];

/** Direction folders generated for Rafe (rotations + walk strips). */
const RAFE_DIRS = ['south', 'east', 'north', 'west'];
const RAFE_WALK_FRAMES = 8;

/**
 * Build the URL list for directional character assets.
 * Key scheme: `<name>:rot:<dir>` and `<name>:walk:<dir>:<frame>`.
 * @param {string} name
 */
function directionalUrls(name) {
	/** @type {Record<string, string>} */
	const out = {};
	for (const dir of RAFE_DIRS) {
		out[`${name}:rot:${dir}`] = `/game/${name}/${dir}.png`;
		for (let i = 0; i < RAFE_WALK_FRAMES; i++) {
			out[`${name}:walk:${dir}:${i}`] = `/game/${name}/walk/${dir}/${i}.png`;
		}
	}
	return out;
}

/**
 * Start loading all known sprites (idempotent).
 * @returns {Promise<void>}
 */
export function loadAssets() {
	if (loadPromise) return loadPromise;

	if (typeof Image === 'undefined' || typeof fetch === 'undefined') {
		loadPromise = Promise.resolve();
		return loadPromise;
	}

	const all = { ...SPRITE_URLS, ...directionalUrls('rafe') };
	const entries = Object.entries(all);
	loadPromise = Promise.all(
		entries.map(
			([key, url]) =>
				new Promise((resolve) => {
					const img = new Image();
					img.decoding = 'async';
					img.onload = () => {
						images[key] = img;
						resolve();
					};
					img.onerror = () => resolve();
					img.src = url;
				})
		)
	)
		.then(async () => {
			// Wang tileset corner metadata (drives grass/path transitions)
			try {
				const res = await fetch('/game/tileset.json');
				if (res.ok) {
					const json = await res.json();
					const tiles = json?.tileset_data?.tiles ?? [];
					for (const t of tiles) {
						const c = t.corners;
						const b = t.bounding_box;
						if (!c || !b) continue;
						wangTiles[wangKey(c.NW, c.NE, c.SW, c.SE)] = {
							x: b.x,
							y: b.y,
							w: b.width,
							h: b.height
						};
					}
				}
			} catch {
				wangTiles = {};
			}

			// Fallback: slice pure grass/path tiles from the Wang sheet
			const sheet = images.tileset;
			if (sheet && typeof document !== 'undefined') {
				for (const [name, box] of Object.entries(TILE_CROPS)) {
					const tile = cropTile(/** @type {HTMLImageElement} */ (sheet), box.x, box.y, 16, 16);
					if (tile) images[name] = tile;
				}
			}
		});

	return loadPromise;
}

/**
 * Wang lookup key from corner terrains ('u'pper / 'l'ower).
 * @param {string} nw @param {string} ne @param {string} sw @param {string} se
 */
export function wangKey(nw, ne, sw, se) {
	return `${nw}|${ne}|${sw}|${se}`;
}

/**
 * Get the sheet crop for a wang corner combination.
 * @param {string} nw @param {string} ne @param {string} sw @param {string} se
 */
export function getWangTile(nw, ne, sw, se) {
	return wangTiles[wangKey(nw, ne, sw, se)] ?? null;
}

/** True when the full 16-corner tileset metadata is available. */
export function hasWangSet() {
	return Object.keys(wangTiles).length >= 16;
}

/** @returns {CanvasImageSource | null} */
export function getTilesetSheet() {
	return images.tileset ?? null;
}

/**
 * Wang tileset crop boxes (from tileset.json bounding_box).
 * lower = pure path, upper = pure grass. Used only as fallback when
 * tileset.json metadata is unavailable.
 */
const TILE_CROPS = {
	path: { x: 32, y: 16 }, // all-lower corners
	grass: { x: 0, y: 48 } // all-upper corners
};

/**
 * @param {HTMLImageElement} sheet
 * @param {number} sx
 * @param {number} sy
 * @param {number} w
 * @param {number} h
 * @returns {HTMLCanvasElement | null}
 */
function cropTile(sheet, sx, sy, w, h) {
	try {
		const c = document.createElement('canvas');
		c.width = w;
		c.height = h;
		const ctx = c.getContext('2d');
		if (!ctx) return null;
		ctx.imageSmoothingEnabled = false;
		ctx.drawImage(sheet, sx, sy, w, h, 0, 0, w, h);
		return c;
	} catch {
		return null;
	}
}

/**
 * @param {string} key
 * @returns {CanvasImageSource | null}
 */
export function getSprite(key) {
	return images[key] ?? null;
}

/**
 * Resolve a directional sprite for a character, preferring walk frames.
 * @param {string} name sprite family (e.g. 'rafe')
 * @param {'south'|'east'|'north'|'west'} dir facing
 * @param {boolean} walking currently mid-walk cycle
 * @param {number} walkFrame frame index (0..RAFE_WALK_FRAMES-1)
 * @returns {CanvasImageSource | null}
 */
export function getDirectionalSprite(name, dir, walking = false, walkFrame = 0) {
	if (walking) {
		const k = `${name}:walk:${dir}:${((walkFrame % RAFE_WALK_FRAMES) + RAFE_WALK_FRAMES) % RAFE_WALK_FRAMES}`;
		if (images[k]) return images[k];
	}
	return images[`${name}:rot:${dir}`] ?? null;
}

/** True if any directional rotation exists for the given sprite family. */
export function hasDirectionalSet(name) {
	return RAFE_DIRS.some((d) => images[`${name}:rot:${d}`] !== undefined);
}

/**
 * Draw a sprite centered on a 16×16 tile footprint (may be larger than tile).
 * @param {CanvasRenderingContext2D} ctx
 * @param {string} key
 * @param {number} px left of tile in buffer pixels
 * @param {number} py top of tile in buffer pixels
 * @param {{ size?: number, bob?: number, flipX?: boolean }} [opts]
 * @returns {boolean} true if drawn
 */
export function drawSprite(ctx, key, px, py, opts = {}) {
	const img = images[key];
	if (!img) return false;

	const size = opts.size ?? 16;
	const bob = opts.bob ?? 0;
	const ox = px + (16 - size) / 2;
	const oy = py + (16 - size) / 2 + bob - Math.max(0, (size - 16) * 0.35);

	ctx.imageSmoothingEnabled = false;
	if (opts.flipX) {
		ctx.save();
		ctx.translate(ox + size / 2, oy);
		ctx.scale(-1, 1);
		ctx.drawImage(img, -size / 2, 0, size, size);
		ctx.restore();
	} else {
		ctx.drawImage(img, ox, oy, size, size);
	}
	return true;
}

/**
 * Draw an image (not necessarily in the registry) centered on a tile footprint.
 * @param {CanvasRenderingContext2D} ctx
 * @param {CanvasImageSource} img
 * @param {number} px
 * @param {number} py
 * @param {{ size?: number, bob?: number, flipX?: boolean }} [opts]
 */
export function drawImageCentered(ctx, img, px, py, opts = {}) {
	const size = opts.size ?? 16;
	const bob = opts.bob ?? 0;
	const ox = px + (16 - size) / 2;
	const oy = py + (16 - size) / 2 + bob - Math.max(0, (size - 16) * 0.35);
	ctx.imageSmoothingEnabled = false;
	if (opts.flipX) {
		ctx.save();
		ctx.translate(ox + size / 2, oy);
		ctx.scale(-1, 1);
		ctx.drawImage(img, -size / 2, 0, size, size);
		ctx.restore();
	} else {
		ctx.drawImage(img, ox, oy, size, size);
	}
}

/**
 * Map NPC face / id to sprite key.
 * @param {{ id?: string, face?: string, dialogueKey?: string, name?: string }} npc
 */
export function spriteKeyForNpc(npc) {
	const id = npc.id ?? '';
	const face = npc.face ?? '';
	const key = npc.dialogueKey ?? '';

	if (id === 'zeno' || face === 'zeno' || key === 'zeno') return 'zeno';
	if (id === 'nala' || face === 'fire' || key === 'nala') return 'nala';
	if (id === 'razel' || face === 'wind' || key === 'razel') return 'razel';
	if (id === 'tidekeeper' || face === 'water' || key === 'tidekeeper') return 'tidekeeper';
	if (face === 'healer' || key === 'healer' || id.includes('healer')) return 'fountain';
	if (face === 'elder' || key === 'elder_pyra') return 'nala';
	if (face === 'guard' || key === 'guard') return 'zeno';
	if (face === 'merchant' || key === 'merchant') return 'razel';
	return 'rafe';
}

/**
 * Map enemy to sprite key.
 * @param {{ id?: string, isBoss?: boolean, name?: string }} enemy
 */
export function spriteKeyForEnemy(enemy) {
	if (enemy.isBoss || enemy.id === 'erebus' || (enemy.name ?? '').includes('Erebus')) {
		return 'erebus';
	}
	return 'shade';
}
